first successful run using the sstools-gb which

diff --git a/bin/sstools-gb b/bin/sstools-gb
--- a/bin/sstools-gb
+++ b/bin/sstools-gb
@@ -4,7 +4,13 @@ sstools_modifier=$1
 #echo ${sstools_modifier}
 #execute global config file to get most up to date configurations
 #Not the most beautiful way to set an environmental variable but it works
-SSTOOLS_ROOT_ENV="${PWD%/bin}"
+
+CURDIR=`/bin/pwd`
+BASEDIR=$(dirname $0)
+ABSPATH=$(readlink -f $0)
+ABSDIR=$(dirname $ABSPATH)
+
+SSTOOLS_ROOT_ENV="${ABSDIR%/bin}"
 export SSTOOLS_ROOT_ENV=${SSTOOLS_ROOT_ENV}
 #export paths in main-conf
 source ${SSTOOLS_ROOT_ENV}/config/config-main.conf
@@ -14,15 +20,28 @@ source ${SSTOOLS_ROOT_ENV}/config/config-user.conf
 
 
 #${SSTOOLS_ROOT_ENV}/modules/bash-modules/sstools-init-modules/sstools-gb-init.sh "$( IFS=$' '; echo "${userarr[*]}" )"
-ARGS_TO_RFUNC=($(${SSTOOLS_ROOT_ENV}/modules/bash-modules/sstools-init-modules/sstools-gb-init.sh "$( IFS=$' '; echo "${userarr[*]}" )"))
-
-#run script based on modifier
-if [ "$sstools_modifier" == "which" ]; then
-  #echo "${ARGS_TO_RFUNC[@]}"
-  ${SSTOOLS_RSOFT}/Rscript ${SSTOOLS_GB_WHICH_RSCRIPT} "${ARGS_TO_RFUNC[@]}"
-elif [ "$sstools_modifier" == "lookup" ]; then
-  #echo "${ARGS_TO_RFUNC[@]}"
-  ${SSTOOLS_RSOFT}/Rscript ${SSTOOLS_GB_LOOKUP_RSCRIPT} "${ARGS_TO_RFUNC[@]}"
+ARGS_TO_RFUNC=($(${SSTOOLS_ROOT_ENV}/modules/bash-modules/sstools-init-modules/sstools-gb-init.sh "$( IFS=$' '; echo "${userarr[*]}" )")) 
+RESULT=$?
+#If the above (most recent command) was successful, then 
+if [ $RESULT -eq 0 ]; then
+  #echo "parsing complete" 1>&2
+  #run script based on modifier
+  if [ "$ARGS_TO_RFUNC" == "" ]; then
+    echo "parsing complete script no output" 1>&2
+    exit 1
+  else
+    if [ "$sstools_modifier" == "which" ]; then
+      #echo "${ARGS_TO_RFUNC[@]}"
+      ${SSTOOLS_RSOFT}/Rscript ${SSTOOLS_GB_WHICH_RSCRIPT} "${ARGS_TO_RFUNC[@]}"
+    elif [ "$sstools_modifier" == "lookup" ]; then
+      echo "${ARGS_TO_RFUNC[@]}"
+      #${SSTOOLS_RSOFT}/Rscript ${SSTOOLS_GB_LOOKUP_RSCRIPT} "${ARGS_TO_RFUNC[@]}"
+    else
+      echo "no modifier" 1>&2
+    fi
+  fi
+else
+  echo "parsing failed" 1>&2
+  exit 1
 fi
-
 
